#####################
### Server Config ###
#####################


# These settings will use around 500-600MB memory when used with the launch script

# Best left on, some memory can be save by disabling
# Disabling will block from receiving data every time it writes the blockBuffer
# Offers around a 10-15% Speed increase for ~3x the memory used
# Helps a lot when writing to slower HDDs



# If using or have a system with multiple nics you may need to explicitly bind to an address
# Can also be used to run multiple instances on different nics
bindAddress: "localhost"

separateThreadForWriting: true

# Max queue size when using separateThreadForWrite
queueSize: 8

# Indifferent to trailing slash, you may need to escape backslashes on windows
outputDirectories:
- "/dir"
- "/dir2/"

# Will only initiate one transfer to a directory at at time regardless of free space
limitOneTransferPerDirectory: true

# Port to use
port: 9988


# Do not include the . only the extension name ex. "plot" not ".plot"
deletedFileTypes:
- "filetype"


# Directories who files are subject to deletion if they meet the filetype and size requirements
deletionDirectories:
- "/dir1"
- "/dir2/"

# Delete files from the specified deletion directory if they meet the type and size requirements
deleteForSpace: false


# Threshold in MiB for files to delete, any files larger than this will be deleted
# When loading the cvonfig this will display as bytes, but input as MiB
deletionThreshHold: 9999999 #MiB


# Overwrite file if it exists.
overWriteExisting: true
