#####################
### Client Config ###
#####################

# These settings will uses 80-110MB of memory while transfering if using the launch script

# Read file from a separate thread, helps when writing to the disk while transfering
separateThreadForReading: true

# Address and port of server receiving the files
serverAddress: "localhost"
serverPort: 9988

# How many transfer to have open at once
maxTransfers: 3

# How often to check for new files in seconds
fileCheckInterval: 15


# Length of block queue when using separateThreadForReading
# readQueueSize * blockSize = maxData in memory at once
readQueueSize: 8

# Directories search at fileCheckInterval, indifferent to tailing slash, may need to escape backslash on windows
monitoredDirectories:
- "/dir/"

# File types that are monitored for to send do not include . prefix, ex. use "plot" not ".plot"
monitoredFileTypes:
- "filetype"


# Delete local files after successful transfers
# Server relays if file was sucessfully transfered and size match
# this will delete on that message
deleteAfterTransfer: true

